//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCBookStore.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVCBookstoreEntities : DbContext
    {
        public MVCBookstoreEntities()
            : base("name=MVCBookstoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_KITAPLAR> TBL_KITAPLAR { get; set; }
        public virtual DbSet<TBL_YAZARLAR> TBL_YAZARLAR { get; set; }
    }
}
